name: Create PR via GH CLI

on:
  workflow_dispatch:
    inputs:
      pr_reviewee:
        type: choice
        description: Choose PR Reviewer
        required: true
        options:
          - aarifmohd1
          - abc
          - xyz
          - abc/xyz

jobs:
  create-pr:
    runs-on: ubuntu-latest
    env:
      PR_APPROVER: ${{ github.event.inputs.pr_reviewee }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          echo "APPROVER=${{ env.PR_APPROVER }}" >> $GITHUB_ENV

      - name: Create a new branch
        run: |
          git checkout -b feature-branch
          git push -u origin feature-branch

      - name: Add a file and commit
        run: |
          echo "This is a test file" > abc.txt
          git add abc.txt
          git commit -m "Added abc.txt"
          git push origin feature-branch

      - name: Create a Pull Request using GH CLI
        run: |
          gh pr create --title "My New Feature" \
                       --body "This is a new feature PR." \
                       --base main \
                       --head feature-branch \
                       --reviewer "${{ env.PR_APPROVER }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Assign Reviewer to PR
        run: |
          PR_NUMBER=$(gh pr view feature-branch --json number --jq '.number')
          echo "Pull Request Number: $PR_NUMBER"
          gh pr edit $PR_NUMBER --add-reviewer "${{ env.PR_APPROVER }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

