name: Create PR via GH CLI

on:
  workflow_dispatch:  # Manually trigger this workflow

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "Aarif Mohd
          git config --global user.email "aarifmohd59@gmail.com"

      - name: Create a new branch
        run: |
          git checkout -b feature-branch

      - name: Add a file and commit
        run: |
          echo "This is a test file" > abc.txt
          git add abc.txt
          git commit -m "Added abc.txt"
          git push origin feature-branch

      - name: Authenticate GH CLI
        run: gh auth login --with-token <<< "${{ secrets.TEAM_GITHUB_TOKEN }}"

      - name: Create a Pull Request using GH CLI
        run: |
          gh pr create --title "My New Feature" \
                       --body "This is a new feature PR." \
                       --base main \
                       --head feature-branch

      - name: Assign Reviewer to PR
        run: |
          PR_NUMBER=$(gh pr list --head feature-branch --json number --jq '.[0].number')
          gh pr review $PR_NUMBER --approve
          gh pr edit $PR_NUMBER --add-reviewer your-reviewer-username


# # This is a basic workflow to help you get started with Actions

# name: CI

# # Controls when the workflow will run
# on:
#   # Triggers the workflow on push or pull request events but only for the "main" branch
#   # push:
#   #   branches: [ "main" ]
#   # pull_request:
#   #   branches: [ "main" ]

#   # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   # This workflow contains a single job called "build"
#   build:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v4

#       # Runs a single command using the runners shell
#       - name: Run a one-line script
#         run: echo Hello, world!

#       # Runs a set of commands using the runners shell
#       - name: Run a multi-line script
#         run: |
#           echo Add other actions to build,
#           echo test, and deploy your project.

#       - name: create-pr
#         run: |
#           # SCRIPT_OUTPUT=$(cat script.log)
#           # rm script.log
#           git checkout -b feature_branch
#           touch abc.txt
#           git add .
#           git commit -m "ci: promote services"
#           git push origin feature_branch
#           git config  user.name "Aarif Mohd"
#           git config  user.email "aarifmohd59@gmail.com"
#           gh pr create --base main --head feature_branch --title "ci: promote services" --body "Promote dev to test
#           #Triggered by: ${{ github.actor }}

